add redirects between microservices
bmstu-secret-chat/secret_chat-orchestrator pull request #7
Opened 2024-12-12 08:47 UTC by arklem699

2024-12-12 19:18 UTC, DriverOnLips commented on nginx.conf
> +            proxy_set_header Upgrade $http_upgrade;
думаю, тут и везде кроме реалтайма сокеты не нужны

2024-12-12 19:19 UTC, DriverOnLips commented on windows/nginx.conf
> +            proxy_set_header Upgrade $http_upgrade;
тут тоже нужно убрать сокеты

2024-12-12 19:20 UTC, DriverOnLips requested changes
поправь комменты

2024-12-12 21:24 UTC, arklem699 commented on nginx.conf
> +            proxy_set_header Upgrade $http_upgrade;
исправил

2024-12-12 21:25 UTC, arklem699 commented on windows/nginx.conf
> +            proxy_set_header Upgrade $http_upgrade;
исправил

2024-12-29 14:25 UTC, DriverOnLips requested changes
нужно резолверы для микросервисов добавить: /backend, /real, /auth. для линукса точно, не думаешь?

2024-12-31 19:47 UTC, DriverOnLips approved these changes

2024-12-31 19:47 UTC, merged